INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('AHRENSFELDE', 'Arnsfelde', 1375, NULL, 'Landbuch s. 69, 116');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('AHRENSFELDE', 'Arnsfelt', 1375, NULL, 'Landbuch s. 69, 116');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('ANITZ', 'Anitz', 1801, NULL, 'Bratring II s. 250');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('ANNAHOF', 'Annahof', 1869, NULL, 'Amtsblatt der Regierung Potadam s. 134');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('GROSSBARNIM', 'Groten Barnym', 1450, NULL, 'Schoßregister s. 74');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('KLEINBARNIM', 'Cleyne Barnym', 1454, NULL, 'A XII 107');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('HEUBARNIM', 'Beu Barnim', 1764, NULL, '~.Br.Rep. 2, D.19849');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BASDORF', 'Bartoldistorp', 1302, NULL, 'A X 225');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BATZLOW', 'Batzelow', 1480, NULL, 'Schoßregister s. 52');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BEIERBDORF', 'in Begerstorp', 1335, NULL, 'A XIII 24? Or');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BERGHOF', 'Berghoff', 1824, NULL, 'Amtsblatt der Regierung Potadam s. 141');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BERGLUCH', 'auf dem Berg Luche', 1750, NULL, 'Pr.Br.Rep. 2, D.15743');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BERLIN-KAROW', 'caro', 1459, NULL, 'A VIII 418');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BERLIN-LÜBARS', 'Libars', 1541, NULL, 'A XI 483 Or');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BERLIN-LÜBARS', 'Lipars', 1541, NULL, 'A XI 483 Or');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BERLIN-MALCHOW', 'Malgow', 1450, NULL, 'Schoßregister s. 49');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BERLIN-WITTENAU', 'Doldorff', 1375, NULL, 'Landbuch s. 70 und 111');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BERLIN-WITTENAU', 'Daldorp', 1375, NULL, 'Landbuch s. 70 und 111');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BERNÖWE', 'Baerenböhe (Pr.Br.Rep. 2', 1754, NULL, 'Pr.Br.Rep. 2, 8.2294/3, fol 1-4');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BERNÖWE', 'D.2546', 1754, NULL, 'Pr.Br.Rep. 2, 8.2294/3, fol 1-4');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BERNÖWE', 'fol 1~', 1754, NULL, 'Pr.Br.Rep. 2, 8.2294/3, fol 1-4');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BERNÖWE', '1797 Bernöwe', 1754, NULL, 'Pr.Br.Rep. 2, 8.2294/3, fol 1-4');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BETHESDA', 'Beystorff', 1541, NULL, 'Steuerregister fol 8');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BERLIN-BIESDORF', 'Beystorp', 1541, NULL, 'Steuerregister fol 4');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BIESELHAUS', 'Bieselhaus', 1797, NULL, 'Pr.Br.Rep. 2, s. 2294/3, fol 1-4');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BIESOW', 'Byso', 1375, NULL, 'Landbuch S. 69, 134');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BIESOW', 'Bysow', 1375, NULL, 'Landbuch S. 69, 134');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BIESOW', 'tho Bisso', 1510, NULL, 'A XI 468 Or');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BIRKBUSCH', 'Birk Busch', 1762, NULL, 'Pr.Br.Rep. 2, s. 3259');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BIRKENHOF', 'Berkanwerder', 1375, NULL, 'Landbucb s. 69, 117');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BIRKHOLZ', 'Berckholze', 1370, NULL, 'A XII 504 Or');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BIRKHOLZAUE', 'Birkhorst', 1845, NULL, 'Amtsblatt der Regierung Potadam s. 204');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BISCHOFSWERDER', 'Biscboffswerder', 1797, NULL, 'Pr.Br.Rep. 2, s. 2294/3, fol 1-4');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BISMARK', 'Bismarck', 1885, NULL, 'Amtsblatt der Regierung Potsdam s. 14');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BERLIN-BLANKENFELDE', 'Johannes de Blankenfalte', 1284, NULL, 'Berliner Ratmann');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BLIESDORF', 'Bliesdorf', 1928, NULL, 'Amtsblatt der Regierung Potadam s. 350');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BLUMENTHAL', 'Blumendal', 1375, NULL, 'Landbuch s. 69 und 133');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('GROSS-BÖHMERHEIDE', 'Groß-Böhmerheide', 1861, NULL, 'Ortschaftsstatistik s. 84');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('KLEIN-BOHMERHEIDE', 'Klein Böhmerheide', 1861, NULL, 'Ortschaftsstatistik s. 72');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BOGEN', 'aufm Bogen', 1740, NULL, 'Pr.Br.Rep 7 Amt Mühlenback Nr.');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BOLLENSDORF', 'Boldenstorp', 1541, NULL, 'Steuerregister fol 2');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BOLLERSDORF', 'Bollersdorff', 1772, NULL, 'Pr.Br.Rep. 2, S.8591, fol 49');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BONE', 'Borgestorp', 1541, NULL, 'Steuerregister fol 5');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BERLIN-BORSIGWALDE', 'Borsigwalde', 1899, NULL, 'Amtsblatt der Regierung Potsdam s. 378');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BREDEWISCH', 'Bredenwisc', 1249, NULL, 'A X 205 Or');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BROICHSDORF', 'Broichsdorff', 1791, NULL, 'Pr.Br.Rep. 2, 8.2294/1, fol 101-104');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BRUCHMUHLE', 'BruckmoliJe', 1428, NULL, 'A XXIV 418 Or');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BERLIN-BUCH', 'Jobannes Buch', 1289, NULL, 'Berliner Ratmann');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BERLIN-BUCH', 'czu Windischen Buck', 1412, NULL, 'C I 50');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('ALT BUCHHORST', 'Alt-Buchholz', 1801, NULL, 'Bratring II s. 252');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('NEU BUCHHORST', 'Neu-Bucbbolz', 1801, NULL, 'Bratring II s. 252');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BUCKOW', 'vom Buckouschen Theeroffen', 1744, NULL, 'Pr.Br.Rep. 2, F.856');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BÜCKLEIN', 'Blichlein', 1831, NULL, 'Amtsblatt der Regierung Potadam s. 37');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('DAHLWITZ-HOPPEGARTEN', 'Dalewitz', 1450, NULL, 'Scboßregister s. 39');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('DAMIEOW', 'der Damkow', 1485, NULL, '');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('DAMMHAUS', 'Dammhaus', 1801, NULL, 'Bratring II s. 254');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('DAMMKRUG', 'Dammkrug', 1834, NULL, 'Pr.Br.Rep. 37 Friedland Nr. 188');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('DAMMÜBLE', 'Damm-Mühle', 1587, NULL, 'Pr.Br.Rep. 37 Friedland Nr. 248, Kop');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('DANNENBERG/MARK', 'Dannenberge', 1375, NULL, 'Landbuch s. 70, 72, 145');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('DANNENBERG/MARK', 'Tannenberg', 1375, NULL, 'Landbuch s. 70, 72, 145');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('DORNBUSCHMÜHLE', 'Dornepusch', 1375, NULL, 'Landbuch s. 134');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('DRAHTHAMMERSCHLEUSE', 'Drahthammer-Schleuse', 1861, NULL, 'Ortschaftsstatistik s. 52');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('DUSTERLAKE', 'Düsterlake', 1801, NULL, 'Bratring II s. 201');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('EBERSBERG', 'Eversberch', 1300, NULL, 'Krabbo Nr. 1788 nach Or');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('NICHENBRANDT', 'Eiebenbrand', 1860, NULL, 'Amtsblatt der Regierung Potadam s. 348');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('EICHHEIDE', 'F. Eichheide', 1884, NULL, 's.');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('EISENHAMMER', 'Eisenspalterey', 1719, NULL, 'Pr.Br.Rep. 2, D.5775');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('ELISENAU', 'Elisenau', 1825, NULL, 'Amtsblatt der Regierung Potadam s. 100');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('ELISENHOF', 'Elisenshoff', 1831, NULL, 'Amtsblatt der Regierung Potadam s. 37');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('ELSENECK', 'Elseneck', 1841, NULL, 'Ortschaftsverzeicbnis b. 27');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('EMILIENFELDE', 'Emilienfelde', 1880, NULL, 'Amtsblatt uer Regierung Potadam S. 299');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('ERNSTHOF', 'Ernsthof', 1833, NULL, 'Amtsblatt der Regierung Potadam s. 166');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('FÄNGERSEE', 'Herr Hasse von Falkenberg', 1349, NULL, 'A XI 39');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('FALKENBERG/MARK', 'Balkenberg', 1450, NULL, 'Schoßregister s. 62');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('FANGSCHLEUSE', 'auf der Fang-Schleuse', 1750, NULL, 'Pr.Br.Rep. 2, D.15743');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('FELDBEIM', 'Feldheim', 1857, NULL, 'Amtsblatt der Regierung Potadam s. 383');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('FICHTEHAU', 'll''ichtenau', 1896, NULL, 'Amtsblatt der Regierung Potadam s. 82');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('HOHDFIBOW', 'Finowfurt', 1929, NULL, 'Amtsblatt der Regierung Potadam s. 268');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('NEUFRIEDLAND', 'Neu Friedland', 1826, NULL, 'UrMBl 1?70/3351 Neu-Trebbin');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('FRIEDRICHSBERG', 'Friedrichsberg', 1797, NULL, 'Pr.Br.Rep. 2, S.2294/J, fol 1-4');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BERLIN-FRIEDRICHSHAGEN', 'Friedrichshagen', 1753, NULL, 'Pr.Br.Rep. 2, D.2538, fol 72');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('FISCHERRAUS AM GAMENSEE', 'am Jamensee', 1840, NULL, 'Ortschaftsverzeichnis s. 51');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('ALTGERSDORJ''', 'Neu Gersdorf', 1841, NULL, 'Ortscha~tsverzeichnis s. 50');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('GIELSDORF', 'czu Geiselstorff', 1433, NULL, 'A XI 336');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('GRABOWSEE', 'G.rabowsee', 1903, NULL, 'Amtsblatt der Regierung Potadam s. 145');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('GRATZE', 'Grassow', 1536, NULL, 'Rep. 78 Kopiar Nr. 32, fol 44');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('GROBEN', 'czu der Groben', 1449, NULL, 'A XII 269');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('GRÜNELINDE', 'Grünelinde oder d. Sperlingskrug', 1801, NULL, 'Bratring II s. 202');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('GRÜNENBERG', 'Grünenberg', 1823, NULL, 'Amtsblatt der Regierung Potadam s. 206');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('GRUNOW', 'Grunow', 1375, NULL, 'Landbuch s. 70 und 132');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('GRUNOW', 'Grunaw', 1375, NULL, 'Landbuch s. 70 und 132');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('HAMMERTHAL', 'Hammertbal', 1861, NULL, 'Ortscbaftsstatistik s. 54');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('HASELBERG', 'Haselberg', 1375, NULL, 'Landbuch s. 70 und 131');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('HECKELBERG', 'Heikelwerke', 1340, NULL, '!');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('HECKELBERG', 'Heckalberg', 1416, NULL, 'A XIII 137');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('NIEDERHEIDE', 'Niederbaide', 1884, NULL, 'Amtsblatt der Regierung Potadam s. 406');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('HEIDEKRUG', 'Heidekrug', 1843, NULL, 'UrMBl 1911/3549');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BERLIN-HERMSDORF', 'Hermanstorp', 1349, NULL, 'A XII 238');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('HERZHORN', 'Bertzhorn', 1375, NULL, 'Landbuch s. 70 und 132');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('HERZHORN', 'Hertzkorn', 1375, NULL, 'Landbuch s. 70 und 132');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('HIRSCHFELDE', 'Hersvelde', 1375, NULL, 'Landbuch s. 70 und 128');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('HIRSCHFELDE', 'Hersehfelde', 1602, NULL, 'Pr.Br.Rep. 78 Kopiar Nr. 86 fol 137');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('HÖNOW', 'czu Honaw', 1412, NULL, 'C I 55');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('NEUHÖNOW', 'Neu Hönow', 1791, NULL, 'Pr.Br.Rep. 2, 8.2294/1, fol 105-108');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('HORTWINKEL', 'aus dem Hartwinkel', 1788, NULL, 'Pr.Br.Rep. 2, D.15977');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('JÄGERBUDE', 'Jägerbude', 1841, NULL, 'UrMBl 1978/3648 Wernsdorf');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('JAGELS VORWERK', 'Jacobistorp', 1300, NULL, 'Krabbo Nr. 1?88 nach Or');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('JOHANNESHOF', 'Johanneshof', 1866, NULL, 'Amtsblatt der Regierung Potadam s. 168');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('KÄHNSDORF', 'Kenstorf magna', 1375, NULL, 'Landbuch s. 70');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('KÄHNSDORF', 'Kenstorf parva', 1375, NULL, 'Landbuch s. 70');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('KÄHNSDORF', 'Keynstorff', 1517, NULL, 'Rep. 78 Kopiar Nr. 26, fol 68');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('KAGEL', 'Cagel', 1480, NULL, 'Scboßregister s. 48');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('KAGELLUCH', 'Caberluch', 1798, NULL, 'Pr.Br.Rep. 2, S.2294/3, fol 109-114');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('KALKSEE', 'am Kalck see', 1754, NULL, 'Pr.Br.Rep. 2, D.2536, fol 22');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('KARLSLUST', 'Carlslust', 1860, NULL, 'Amtsblatt der Regierung Potadam s. 387');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('KARLSWERK', 'Carlswerk', 1775, NULL, 'Pr.Br.Rep. 2, s. 1906 fol 180');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('KARPENTEICH', 'am Karpen Teich', 1798, NULL, 'Pr.Br.Rep. 2, F.3445, fol 75');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('KATHARINENHOF', 'Catarinenhof', 1817, NULL, 'Ortschaftsverzeichnis II. 84');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('NEUKIETZ', 'Neu Kietz bey Frayenwalde', 1764, NULL, 'Pr.Br.Rep. 21 D.19849');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('KLANDORF', 'Klahndorf', 1811, NULL, 'Amtsblatt der Regierung Potadam s. 124');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('KLOSTERFELDE', 'Closterueld', 1242, NULL, 'A X 201');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('KÖNIGSDAMM', 'auf den Königsdamm', 1801, NULL, 'Pr.Br.Rep. 2, F.4929, fol 176');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('RETTUNGSHAUS KÖTHEN', 'Coethener Heim', 1927, NULL, 'Rettungshaus');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BERLIN-KONRADSHOHE', 'Gonradshöhe', 1868, NULL, 'Amtsblatt der Regierung Potadam s. 342');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('KREUZBRUCH', 'im Creutz Bruche', 1717, NULL, 'Pr.Br.Rep. 2, D.11855');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('KUHBRÜCKE', 'Kuhbrücke', 1839, NULL, 'UrMBl 1692/3245 Oranienburg');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('KUNICKENDORF', 'Kunickendorff', 1770, NULL, 'Pr.Br.Rep. 2, S.7835, fol 1');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('KUPFERHAMMERSCHLEUSE', 'Kupferhammer-Schleuse', 1861, NULL, 'Ortschaftsstatistik s. 60');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('LANDHOF', 'Landhof', 1830, NULL, 'R.Schmidt, Die Herrschaft Friedland, s. 118');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('LANKE', 'Ie.nke', 1375, NULL, 'Landbuch s. 45 70 und 144');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('LANKE', 'Lancke', 1375, NULL, 'Landbuch s. 45 70 und 144');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('ALTLEWIN', 'Louwin', 1412, NULL, 'C I 54');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('ALTLEWIN', 'Lewynn', 1541, NULL, 'Steuerregister fol 7');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('LICHTERFELDE', 'Lichterfalte', 1277, NULL, 'Krabbo Nr. 1114 nach Or');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('LICHTERFELDE', 'in villa L~chteruelde', 1334, NULL, 'A XI 306');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('FÖRSTEREI LIEPNITZ', 'an der Liepnitz', 1775, NULL, 'Büsching s. 161');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('LINDOW', 'Lindow', 1406, NULL, 'Pr.Br.Rep. 8 Bernau U 6, A XII 168 Or');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('LOBETAL', 'Lobethal', 1920, NULL, 'Amtsblatt der Regierung Potsdam s. 60');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('LUPINENHOF', 'Lupinenhof', 1857, NULL, 'Amtsblatt der Regierung Potsdam, s. 39');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('MACHERSLUST', 'Macherslust', 1801, NULL, 'Bratring II s. 264');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('NEUMÄDEWITZ', 'Neu Madewitz', 1764, NULL, 'Pr.Br.Rep. 2, D.19849');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('MALZMÜHLE', 'in der Maltzmtihle', 1674, NULL, 'Pr.Br.Rep. 8 Wriezen Nr. 208');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('MAXBERG', 'Maxberg', 1860, NULL, 'Amtsblatt der Regierung Potsdam s. 375');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('MEHROW', 'Mero', 1541, NULL, 'Steuerregister fol 2');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('METZDORF', 'Mezdorff', 1624, NULL, 'Schoßkataster fol 322');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('MÖNCHMÜHLE', 'Hennikes Molne', 1242, NULL, 'AX 201');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('MÜGGELSEE', 'an der Müggel', 1744, NULL, 'Pr.Br.Rep. 2, F.856');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BERLINER MÜHLE', 'Berlinische Mühle', 1680, NULL, 'Pr.Br.Rep. 2, D.3820');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('KLEINE MÜHLE', 'dy Lubenneke', 1366, NULL, 'A XII 421 Or');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('LAPENOWER MÜHLE', 'Karknieehe', 1549, NULL, '!');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('MITTELMÜHLE', 'Vorde', 1360, NULL, 'A XII 301');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('PRITZHAGENER MÜHLE', 'Mollenbake', 1450, NULL, 'Schoßregister s. 49');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('NASSENHEIDE', 'die Nateheide', 1350, NULL, 'A IV 56 Or');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('NEUERÜCK', 'Neubrück', 1797, NULL, 'Pr.Br.Rep. 2, S.2294/3, fol 9-12');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('NEUENDORF', 'Nygendorp', 1350, NULL, 'A IV 56 Or');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('NEUHOLLAND', 'Neuholland', 1708, NULL, 'Pr.Br.Rep. 2, D.15054, fol 66');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('ORANIENBURG', 'Bötzow', 1298, NULL, 'A VII 201');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('ORANIENBURG', 'Bottzow', 1375, NULL, 'eb. s. 33 und 64');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('ORANIENBURG', 'B~tzow', 1375, NULL, 'eb. s. 33 und 64');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('PAPENMÜHLE', 'Pfafmulle', 1608, NULL, 'Pr.Br.Rep. 78, Nr. 83');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('POHLITZMÜHLE', 'Polenzwarder', 1775, NULL, 'Büsching s. 211');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('PRIESTERSEE', 'Am Priestersee', 1801, NULL, 'Bratring II s. 266');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('PRÖTZEL', 'Pretzel', 1450, NULL, 'Schoßregister s. 71');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('RADEBRÜCK', 'Radebrück', 1795, NULL, 'Pr.Br.Rep. 2, D.3762, fol 151');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('RÄCKSHOF', 'Räckshof', 1841, NULL, 'Ortschaftsverzeichnis s. 55');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('BERLIN-RAHNSDORF', 'Ranstorff', 1541, NULL, 'Steuerregister fol 6');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('ALTRANFT', 'Ranfft', 1450, NULL, 'Schoßregister s. 56');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('RAVENSTEIN', 'dy Rabensteynischen Mole', 1457, NULL, 'A XII 23');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('REHBERGE', 'Rehberge', 1823, NULL, 'Amtsblatt der Regierung Potsdam s. 150');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('REHHORST', 'Rehhorst', 1817, NULL, 'Ortschaftsverzeichnis I. 55');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('REIOBENOW', 'Richenow! R;ycbenow', 1375, NULL, 'Iandbuch s. 50, 51, 71 und 135');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('RICHARDSDORF', 'RichardSdorff', 1770, NULL, 'Pr.Br.Rep. 2, S.7835, fol 1');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('RINGENWALDE', 'Ringbenwalde', 1375, NULL, 'Iendbucb s. 127 und 71');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('RINGENWALDE', 'Ryngenwalde', 1375, NULL, 'Iendbucb s. 127 und 71');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('RONDEL', 'Rondel', 1861, NULL, 'vorm. Vorw. Winkel');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('ROTEHOF', 'Rothehof', 1861, NULL, 'Rothe Mühle');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('RUHLSDORF', 'Ruelstorff', 1541, NULL, 'Steuerregister fol 11');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('RUMMELSBURG', 'Rummelsburg', 1797, NULL, 'Pr.Br.Rep. 2, 8.2294/3, fol 27-30');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('SOREWENFLAGGE', 'Schildow', 1375, NULL, 'Landbuch s. 71 und 125');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('SCRIPFURT', 'Schlag od. Heidekrug', 1801, NULL, 'Bratring ~I s. 268');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('SCHLAGMÜHLE', 'SchlagmUhle', 1775, NULL, 'Büsching s. 276');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('LEESENBRÜCKER SCHLEUSE', 'Laesenbrück', 1797, NULL, 'Pr.Br.Rep. 2, S.2294/3, :fol 5-B');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('MALZER SCHLEUSE', 'Malzer Schleuse', 1841, NULL, 'Ortscbaftsverzeichnis s. 33');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('SCHMACHTENHAGEN', 'Smachtenhagen', 1350, NULL, 'A IV 56 Or');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('SCHMALENBERG', 'Scbmallenberg', 1798, NULL, 'Pr.Br.Rep. 2, S.2294/3, fol 109-114');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('SCHMETZDORF', 'Smidsdorff', 1434, NULL, 'Pr • .Hr.Rep. 8 Bernau U 12 Or; A XII 174 Or');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('SCHNEIDEMÜHLE', '~osschonbeke', 1608, NULL, 'Pr.Br.Rep. 78 Kopiar Nr. 83, fol 235');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('SCHÖNERLINDE', 'Scbonrelinde', 1450, NULL, 'Scboßregister s. 51');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('SCHÖNHOLZ', 'to Schonenholte', 1441, NULL, 'C I 246');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('SCHONWALDE WEST', 'Schefforde', 1450, NULL, 'Schoßregister s. 55');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('SCHULZENHÖHE', 'Schulzenhöbe', 1822, NULL, 'Amtsblatt der Regierung Potadam s. 20');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('SCHWÄRZE', 'apud Swertzam', 1300, NULL, 'Krabbo Nr. 1?88 nach Or');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('SEEKRUG', 'Seekrug', 1841, NULL, 'Ortschaftsverzeichnis s. 39');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('SOPHIENFELDE', 'Bopbienfelde', 1865, NULL, 'Amtsblatt der Regierung Potadam 8.232');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('SPECHTHAUSEN', 'zu Spechtsbausen', 1709, NULL, 'Pr.Br.Rep. 2, D.6002, fol 29');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('SPRINGEBERG', 'Spring Berg', 1753, NULL, 'Pr.Br.Rep. 2, D.10655');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('STEINEECK', 'Steynbeke', 1375, NULL, 'Landbucb s. 71 und 151');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('STEINEECK', 'Stenbeke', 1375, NULL, 'Landbucb s. 71 und 151');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('STOLZENHAGEN', 'Stoltenhagen', 1244, NULL, 'Pr.Br.Rep. 10 B Lehnin U 14 Or; Krabbo Nr. 694');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('STOLZENHAGENSEE', 'Thomas Wall am Storekawaehen Pforth', 1749, NULL, 'Pr.Br.Rep. 2, D.15930');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('STRUWENBERG', 'Struvenberg', 1791, NULL, 'Pr.Br.Rep. 2, S.2294/1, fol 101-104');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('TASSDORF', 'Tastarff', 1375, NULL, 'Landbuch s. 71');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('TASSDORF', 'Tastorff', 1375, NULL, 'Landbuch s. 71');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('TEGELGRUND', 'Tegelgrund', 1861, NULL, 'Ortschaftsstatistik s. 88');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('TEMPELFELDE', 'Tempelveld', 1375, NULL, 'Landbuch s. 71 und 138');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('TEMPELFELDE', 'Tempelfelt', 1375, NULL, 'Landbuch s. 71 und 138');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('TEMPELFELDE', 'Tempelfeldt', 1375, NULL, 'Landbuch s. 71 und 138');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('TEMPELFELDE', 'Tempelvelde', 1375, NULL, 'Landbuch s. 71 und 138');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('THAERFELDE', 'Thärfelde', 1842, NULL, 'Amtsblatt der Regierung Potadam s. 252');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('TIERGARTENSCHLEUSE', 'Thiergartenmühle', 1817, NULL, 'Ortschaftsverzeiehnis I. Nr. 101');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('TORFHAUS', 'Torfhaus', 1841, NULL, 'Ortschaftsverzeichnis s. 45');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('TORGOW', 'Wilhelmus de Tornow', 1275, NULL, 'A XIII 219 Or');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('ALTTORNOW', 'Tor.now', 1414, NULL, 'A XII 385 Kop');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('TRAPPENFELDE', 'Trappenfelde', 1888, NULL, 'Amtsblatt der Regierung Potsdam, s. 36');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('ALTTREBBIN', 'Trebineken', 1349, NULL, 'A XII 493, ?');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('TREUENH0F', 'Treuenhof', 1866, NULL, 'Amtsblatt der Regierung Potadam s. 168');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('TUCHEN', 'zu Tuchen', 1499, NULL, 'C II 432');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('NEUVORWERK', 'Neue Vorwerk', 1817, NULL, 'Ortschaftsverzeichnis I. 31');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('KLEINWALL', 'am Kleinen Wall', 1662, NULL, 'Pr.Br.Rep. 2, D.16306, fol 14');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('WANDLITZ', 'Wandelitz', 1242, NULL, 'A X 200');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('WEESOW', 'Wese', 1375, NULL, 'Landbuch s. 72 und 139');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('WEISSES HAUS', 'Weiße Haus', 1839, NULL, 'UrMBl 1692/3245 Oranienburg');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('WENDTSHOF', 'Wandtehof', 1866, NULL, 'Amtsblatt der Regierung Potadam s. 117');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('WENSICKENDORF', 'Wenßkendorff', 1450, NULL, 'Schoßregister s. 42');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('WERDER', 'Werder', 1375, NULL, 'Landbucb s. 72 und 128');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('GROSS-WERDER', 'Werder', 1791, NULL, 'Pr.Br.Rep. 2, Se2294/1, fol 105-108');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('WESENDAHJJ', 'Wesendal', 1367, NULL, 'Pr.Br.Rep. 8 Strausberg U 23');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('WILDTRÄNKE', 'Wildtränke', 1906, NULL, 'Amtsblatt der Regierung Potadam s. 384');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('WILHELMSBERG', 'Wilhelmsberg', 1878, NULL, 'Amtsblatt der Regierung Potadam s. 36');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('WOLFSTHAL', 'Wolfsthai', 1773, NULL, 'Pr.Br.Rep. 2, S.7835');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('WOLFSWINKEL', 'im Wolffswinckel', 1765, NULL, 'eb. fol 113');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('WOLTERSDORF', 'Walterstorff', 1375, NULL, 'Landbuch s. 72');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('WRIEZEN', 'Wre', 1247, NULL, 'ze');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('WUSCHEWIER', 'Wouschewieher', 1791, NULL, 'Pr.Br.Rep. 2, s.2294/1, f''ol 101-104');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('ZAINHAMMER', 'Zainhammer', 1823, NULL, 'Pr.Br.Rep. 7 Biesenthai Nr. 611');
INSERT INTO place_aliases (place_name, alias, year_from, year_to, source) VALUES ('ZEHLENDORF', 'Czelendorff', 1450, NULL, 'Schoßregister s. 37');